// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire red;
wire green;
wire blue;


//=======================================================
//  Structural coding
//=======================================================

assign VGA_R = {'d4{red}};
assign VGA_G = {'d4{green}};
assign VGA_B = {'d4{blue}};
/*
steag1 i_steag1(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag2 i_steag2(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag3 i_steag3(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag4 i_steag4(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag5 i_steag5(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag6 i_steag6(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag7 i_steag7(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag8 i_steag8(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag9 i_steag9(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag10 i_steag10(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag11 i_steag11(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag12 i_steag12(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

steag13 i_steag13(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

cerc1 i_cerc1(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

cerc2 i_cerc2(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

blink_circle i_blink_circle(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);

cerculet_mergator i_cerculet_mergator(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);
*/
toate_steagurile i_toate_steagurile(
  .clk    (MAX10_CLK1_50),
  .rst    (~KEY[0]      ),
  .en     (SW[0]        ),
  .h_sync (VGA_HS       ),
  .v_sync (VGA_VS       ),
  .red    (red          ),
  .blue   (blue         ),
  .green  (green        )

);



endmodule
